[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "@chainlink/contracts/=/home/thernee/Documents/work/w3b-3/lib/chainlink-brownie-contracts/contracts/",
]
# Allow foundry to run commands directly on the machine - for foundry devops
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
